//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Games.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class developerPublisher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public developerPublisher()
        {
            this.game_developerPublisher = new HashSet<game_developerPublisher>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> id_igdb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<game_developerPublisher> game_developerPublisher { get; set; }
    }
}
