//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Games.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GameEntity()
        {
            this.game_developerPublisher = new HashSet<game_developerPublisher>();
            this.game_gender = new HashSet<game_gender>();
            this.game_platform = new HashSet<game_platform>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string nota { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public Nullable<decimal> preco { get; set; }
        public Nullable<int> metacritic { get; set; }
        public int completo { get; set; }
        public string summary { get; set; }
        public string formato { get; set; }
        public string tamanho { get; set; }
        public Nullable<int> id_store { get; set; }
        public Nullable<int> id_rating { get; set; }
        public string cloudnary_id { get; set; }
        public int id_igdb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<game_developerPublisher> game_developerPublisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<game_gender> game_gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<game_platform> game_platform { get; set; }
        public virtual store store { get; set; }
        public virtual rating rating { get; set; }
    }
}
