//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Games.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GameEntity()
        {
            this.game_developerPublisher = new HashSet<game_developerPublisher>();
            this.game_platform = new HashSet<game_platform>();
            this.game_genre = new HashSet<game_genre>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string summary { get; set; }
        public string cloudnary_id { get; set; }
        public Nullable<int> id_igdb { get; set; }
        public bool completo { get; set; }
        public Nullable<decimal> nota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<game_developerPublisher> game_developerPublisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<game_platform> game_platform { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<game_genre> game_genre { get; set; }
    }
}
