//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Games.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_platform
    {
        public int id { get; set; }
        public int id_game { get; set; }
        public int id_platform { get; set; }
    
        public virtual GameEntity game { get; set; }
        public virtual platform platform { get; set; }
    }
}
