//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Games.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GamesEntities : DbContext
    {
        public GamesEntities()
            : base("name=GamesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<developerPublisher> developerPublisher { get; set; }
        public virtual DbSet<GameEntity> game { get; set; }
        public virtual DbSet<game_developerPublisher> game_developerPublisher { get; set; }
        public virtual DbSet<game_gender> game_gender { get; set; }
        public virtual DbSet<game_platform> game_platform { get; set; }
        public virtual DbSet<gender> gender { get; set; }
        public virtual DbSet<platform> platform { get; set; }
        public virtual DbSet<rating> rating { get; set; }
        public virtual DbSet<region> region { get; set; }
        public virtual DbSet<store> store { get; set; }
        public virtual DbSet<status> status { get; set; }
    }
}
